# Generated by Django 4.2.7 on 2024-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='Place_image'),
        ),
    ]
