# Generated by Django 4.2.7 on 2024-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_place_url_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
