# Generated by Django 4.2.7 on 2024-04-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_image_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(upload_to='viewImages'),
        ),
    ]
