# Generated by Django 4.2.7 on 2024-04-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_remove_image_image_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
