# Generated by Django 4.2.7 on 2024-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_Name', models.CharField(max_length=100)),
                ('No_Listing', models.IntegerField()),
            ],
        ),
    ]
