# Generated by Django 4.2.7 on 2024-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
