# Generated by Django 4.2.7 on 2024-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_listing_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('whatsApp', models.URLField(blank=True)),
            ],
        ),
    ]
