# Generated by Django 4.2.7 on 2024-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_rename_images_website_image_icon_website_image_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_image',
            name='Icon',
            field=models.ImageField(blank=True, null=True, upload_to='webImages'),
        ),
        migrations.AlterField(
            model_name='website_image',
            name='Log',
            field=models.ImageField(blank=True, null=True, upload_to='webImages'),
        ),
        migrations.AlterField(
            model_name='website_image',
            name='Name',
            field=models.ImageField(blank=True, null=True, upload_to='webImages'),
        ),
    ]
