# Generated by Django 4.2.7 on 2024-05-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_alter_website_image_icon_alter_website_image_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website_image',
            name='Log',
        ),
        migrations.RemoveField(
            model_name='website_image',
            name='Name',
        ),
    ]
