# Generated by Django 4.2.7 on 2024-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_remove_website_image_log_remove_website_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_image',
            name='Icon',
            field=models.ImageField(default=None, upload_to='webImages'),
        ),
    ]
