# Generated by Django 4.2.7 on 2024-05-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_website_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_image',
            name='Icon',
            field=models.ImageField(default=None, null=True, upload_to='webImages'),
        ),
        migrations.AlterField(
            model_name='website_image',
            name='Log',
            field=models.ImageField(default=None, null=True, upload_to='webImages'),
        ),
        migrations.AlterField(
            model_name='website_image',
            name='Name',
            field=models.ImageField(default=None, null=True, upload_to='webImages'),
        ),
    ]
