# Generated by Django 4.2.7 on 2024-05-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_alter_website_image_icon_alter_website_image_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_image',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.contact'),
        ),
    ]
