# Generated by Django 4.2.7 on 2024-05-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_website_image_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_Wording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True, null=True)),
                ('pricing', models.IntegerField()),
                ('reviews', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.place')),
            ],
        ),
    ]
