# Generated by Django 4.2.7 on 2024-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0025_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
